### ISSUE TITLE
:conc-name and :constructor in structs definition could save some functions

### ISSUE THREAD

**Issue by gwangjinkim** [HenryS1/salmon#8]
Hello!

By the way a nice package! 
The `monad.lisp` file is a beautiful example for a DSL - the `mdo` DSL.
And with the different monads `maybe`, `mlist`, ... , we have created kind of side-languages.
Monads in Lisp are so extremely concise. Beautiful!

I think I will use it if I see a possiblity.

(I was just today morning reading about monads - and I think I understood it now - it was maybe third attempt after long pause - after some confusing explanations in the internet - just a designpattern for composability/chainability despite of some side effects to take care along the pure functions ...).

---

What I want to say is more sth cosmetic - maybe rather relevant is someone wants to do some code golfing :D .

And maybe you know it already:

```
(defstruct just value)

(defun just (v) (make-just :value v))
```

Can be done at once by:
```
(defstruct (just (:constructor just (value))) value)
```
This says: constructor's name is also `just` (in addition to `make-just`) and its lambda list ist `(value).

But you have to access the value with:
```
(defparameter *j* (just 3))
(just-value *j*) ;;=> 3
```

One can however use `:conc-name` and give no prefix:
```
(defstruct (just (:conc-name) (:constructor just (value))) value)
```

Then, this works:
```
(defparameter *j* (just 3))
(value *j*) ;;=> 3
```

Then, the maybe code becomes slighlty shorter:

```
(defpackage :maybe
  (:use :cl :monad)
  (:import-from :monad :fmap :flatmap)
  (:export :just-value
           :just))

(in-package :maybe)

(defstruct just value)

(defun just (v) (make-just :value v))

(defmethod print-object ((just just) out)
  (print-unreadable-object (just out :type t)
    (format out "~a" (just-value just))))

(defmethod fmap (fun (v (eql nil))) v)

(defmethod fmap (fun (just just))
  (just (funcall fun (just-value just))))

(defmethod flatmap (fun (v (eql nil))) v)

(defmethod flatmap (fun (just just))
  (funcall fun (just-value just)))

```

to:

```
(defpackage :maybe
  (:use :cl :monad)
  (:import-from :monad :fmap :flatmap)
  (:export :just
                :value))

(in-package :maybe)

(defstruct (just (:conc-name) (:constructor just (value))) 
  value)

(defmethod print-object ((just just) out)
  (print-unreadable-object (just out :type t)
    (format out "~a" (value just))))

(defmethod fmap (fun (v (eql nil))) v)

(defmethod fmap (fun (just just))
  (just (funcall fun (value just))))

(defmethod flatmap (fun (v (eql nil))) v)

(defmethod flatmap (fun (just just))
  (funcall fun (value just)))
```

Not much shorter but a little bit more concise.
Well, for beginner lisper the original version is probably easier understandable.

One can apply this kind of changes on the other monads definitions, too.

**Comment by HenryS1** [comment]
I'm glad you like the library. I agree that your suggestion simplifies the implementation and I've made the suggested change here https://github.com/HenryS1/salmon/pull/9.
